x-service-templates:
  api: &api
    build:
      context: .
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "100MB"

services:
  api1:
    <<: *api
    ports:
      - "9991:8080"
  api2:
    <<: *api
    ports:
      - "9992:8080"

  pingora:
    build:
      context: modules/load-balancer
    ports:
      - "9999:8080"
    environment:
        - HOSTS=api1:8080,api2:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true