name: rinha_de_backend_2025_dart
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.0

dependencies:
  sqlite3: ^2.7.7
  uuid: ^4.5.1
  shared_kernel:
    path: modules/repository/shared_kernel

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
