name: rinha_de_backend_2025_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqlite3: ^2.7.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
